---

#- name: evasive | Create {{ apache_document_root }} directory
#  file: path={{ apache_document_root }} state=directory
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
#  tags: package

- name: evasive | Install apache mod evasive for denied of service
  apt: pkg={{ item }} update_cache=yes state={{ evasive_pkg_state }}
  sudo: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_mod_evasive_enabled
  tags: package
  with_items:
   - libapache2-mod-evasive

#TODO sudo rm -Rf /etc/apache2/conf.d/
- name: evasive | Add apache mod evasive for denied of service configuration
  template:
    src: "evasive.conf.j2"
    dest: "{{ apache_conf_path }}/mods-available/evasive.conf"
    owner: root
    group: root
    mode: 0644
  sudo: yes
#  notify: restart apache
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_mod_evasive_enabled

- name: evasive | Install apache mod evasive for denied of service for fail2ban
  apt: pkg={{ item }} update_cache=yes state={{ evasive_pkg_state }}
  sudo: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_mod_evasive_enabled
  tags: package
  with_items:
   - fail2ban

- name: evasive | Add apache mod evasive for denied of service configuration for fail2ban (1)
  template:
    src: "apache-evasive.conf.j2"
    dest: "{{ fail2ban_conf_path }}/filter.d/apache-evasive.conf"
    owner: root
    group: root
    mode: 0644
  sudo: yes
#  notify: restart apache
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_mod_evasive_enabled

- name: evasive | Add apache mod evasive for denied of service configuration for fail2ban (2)
  template:
    src: "jail.local.j2"
    dest: "{{ fail2ban_conf_path }}/jail.local"
    owner: root
    group: root
    mode: 0644
  sudo: yes
#  notify: restart apache
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_mod_evasive_enabled

#TODO
#http://blog.mattbrock.co.uk/hardening-the-security-on-ubuntu-server-14-04/
- name: evasive | Install apache mod security
  apt: pkg={{ item }} update_cache=yes state={{ evasive_pkg_state }}
  sudo: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and apache_mod_security_enabled
  tags: package
  with_items:
   - libapache2-modsecurity


